### PR TITLE
Updating commands for Termux

### PR DESCRIPTION
**Pull request by ufgf**

### CODE REVIEW

**Comment by AvinashReddy3108** [comment]
`pip` work fine for me in Termux.

**Comment by ufgf** [comment]
PSX_20200311_190936

And a my friend did have something like this:
photo_2020-03-11_19-09-19

**Comment by AvinashReddy3108** [comment]
> PSX_20200311_190936

I guess the Android version is 5/6? Try to upgrade it.
It's just a warning, can be ignored for now.

> And a my friend did have something like this:
> photo_2020-03-11_19-09-19

Did your friend install Python in Termux? doesn't look like it.

**Comment by ufgf** [comment]
Android version - 9 (both mine and friend)

The python itself is installed and working correctly (apparently almost):
PSX_20200312_195555

**Comment by AvinashReddy3108** [comment]
I guess I'll have to merge these changes here.
Thanks for the PR.

**Pull request merged**
