### PR TITLE
Revert "Updating commands for Termux"

### PR DESCRIPTION
**Pull request by penn5**
Reverts friendly-telegram/friendly-telegram.github.io#7 because it only makes things worse

### CODE REVIEW

**Comment by ufgf** [comment]
And what makes it worse?

**Comment by penn5** [comment]
It defaults to python 2, and the commands I used are consistent with the rest of the tutorial.

**Comment by ufgf** [comment]
And if you use the command: python**3** -m pip?

**Comment by penn5** [comment]
Then it's even more different to your PR. But as python3 doesn't always exist / is the right version, I'm just using the default version.

**Comment by smartmanru** [comment]
Guys, in the termux default python-3.8 [evidence](https://asciinema.org/a/vwAW3uOTv7JkRWxzoGw2sN9qt)

**Pull request merged**
