### PR TITLE
Shameless attempt to add a favicon! -By smyaknti14@gmail.com

### PR DESCRIPTION
**Pull request by smyaknti**
An attempt to make the page display a favicon.

- Soumyakanti (smyaknti14@gmail.com)

### CODE REVIEW

**Comment by penn5** [comment]
@smyaknti https://stackoverflow.com/questions/35037482/favicon-with-github-pages

**Comment by smyaknti** [comment]
@penn5 thats for HTML heads afaik.

**Comment by penn5** [comment]
@smyaknti That's true, but there must be some way

**Comment by penn5** [comment]
@smyaknti https://github.community/t5/GitHub-Pages/How-do-you-add-a-favicon-to-a-GitHub-page-with-a-theme/td-p/25659

**Comment by penn5** [comment]
https://github.community/t5/GitHub-Pages/How-do-you-add-a-favicon-to-a-GitHub-page-with-a-theme/m-p/33115/highlight/true#M2171
Says this will work

**Pull request merged**
